//import router from './router'
import VueAxios from 'vue-axios';
import axios from 'axios';
//import VueSocialauth from 'vue-social-auth';
import VueCookie from 'vue-cookie';
import moment from 'moment';
//import VueCarousel from 'vue-carousel';
//import editor from 'vue2-medium-editor';
//import MediumEditor from 'medium-editor';